#!/usr/bin/env bash

getswd()
{
    ACTUAL_PATH=$(readlink -f "${BASH_SOURCE[0]}") # resolve symlinks
    SCRIPT_DIR=$(dirname "$ACTUAL_PATH")
    echo "$SCRIPT_DIR"
}

help()
{
    "$(getswd)/upvoter-help" "$@"
}

run()
{
    PROGRAM=$1
    shift
    type "$PROGRAM" &> /dev/null && exec "$PROGRAM" "$@"
}

case "$1" in
    '-?'|-h|--help)
        SUFFIX=help
        ;;
    -v|--version)
        SUFFIX=version
        ;;
    *)
        SUFFIX=$1
        ;;
esac

shift

PROGRAM=upvoter-$SUFFIX

if ! run "$PROGRAM" "$@" && ! run "$(getswd)/$PROGRAM" "$@"; then
    help > &2
    exit 1
fi
