#!/usr/bin/env bash

getcmds()
{
    # find all executable files in $(searchdirs) that start with 'upvoter-'
    searchdirs | xargs -i find {} -type f -or -type l -name "upvoter-*" -maxdepth 1 -perm +111
}

getswd()
{
    dirname "$(here)"
}

here()
{
    RESULT=${BASH_SOURCE[0]}

    # resolve symlinks (readlink -f can't be used on OSX)
    while [[ -h $RESULT ]]
    do
        SYMDIR=$(dirname "$RESULT")
        cd -P "$SYMDIR"
        RESULT=$(readlink "$RESULT")
    done

    echo "$RESULT"
}

pathdirs()
{
    # get all dirs in $PATH
    RESULT=${PATH//:/$'\n'} # replace : (delim) with newline
    echo "$RESULT"
}

searchdirs()
{
    pathdirs && getswd
}

version()
{
    "$(getswd)/upvoter-version" "$@"
}

echo 'upvoter is a command-line util that automatically upvotes your Reddit posts.'
echo "Version: $(version)"
echo 'Find us on GitHub at: https://github.com/jamesqo/upvoter'
echo
echo 'Basic usage: upvoter [command] [options]...'
echo
echo 'Commands can be any one of the following:'

getcmds | while read -r COMMAND
do
    echo " - ${COMMAND#upvoter-}"
done

echo
echo 'For more help on a specific command, type `upvoter [command] --help`.'
