#!/usr/bin/env bash

getswd()
{
    dirname "$(here)"
}

help()
{
    "$(getswd)/upvoter-help" "$@"
}

here()
{
    RESULT=${BASH_SOURCE[0]}

    # resolve symlinks (readlink -f can't be used on OSX)
    while [[ -h $RESULT ]]
    do
        SYMDIR=$(dirname "$RESULT")
        cd -P "$SYMDIR"
        RESULT=$(readlink "$RESULT")
    done

    echo "$RESULT"
}

run()
{
    PROGRAM=$1
    shift
    type "$PROGRAM" &> /dev/null && exec "$PROGRAM" "$@"
}

case "$1" in
    '-?'|-h|--help)
        SUFFIX=help
        ;;
    -v|--version)
        SUFFIX=version
        ;;
    *)
        SUFFIX=$1
        ;;
esac

shift

PROGRAM=upvoter-$SUFFIX

if ! run "$PROGRAM" "$@" && ! run "$(getswd)/$PROGRAM" "$@"; then
    help > &2
    exit 1
fi
