#!/usr/bin/env bash

getswd()
{
    dirname "$(here)"
}

here()
{
    RESULT=${BASH_SOURCE[0]}

    # resolve symlinks (readlink -f can't be used on OSX)
    while [[ -h $RESULT ]]
    do
        SYMDIR=$(dirname "$RESULT")
        cd -P "$SYMDIR"
        RESULT=$(readlink "$RESULT")
    done

    echo "$RESULT"
}

exec cat "$(getswd)/../VERSION"
