#!/usr/bin/env bash

getcmds()
{
    # find all executable files/symlinks in $(searchdirs) that start with 'upvoter-'
    # then basename them (yes, the -i is necessary)
    searchdirs |
    xargs -i find -L {} -name 'upvoter-*' -type f -maxdepth 1 -perm +111 2> /dev/null |
    xargs -i basename {}
}

getswd()
{
    dirname "$(here)"
}

here()
{
    RESULT=${BASH_SOURCE[0]}

    # resolve symlinks (readlink -f can't be used on OSX)
    while [[ -h $RESULT ]]
    do
        SYMDIR=$(dirname "$RESULT")
        cd -P "$SYMDIR"
        RESULT=$(readlink "$RESULT")
    done

    echo "$RESULT"
}

pathdirs()
{
    # get all dirs in $PATH
    SPLIT=${PATH//:/$'\n'} # replace : (delim) with newline
    echo "$SPLIT" | xargs ls -1d 2> /dev/null # remove dirs that don't exist
}

searchdirs()
{
    pathdirs
    getswd
}

version()
{
    "$(getswd)/upvoter-version" "$@"
}

echo
echo 'upvoter is a command-line util that automatically upvotes your Reddit posts.'
echo
echo "Version: $(version)"
echo
echo 'Basic usage: upvoter [command] [options]...'
echo
echo 'Commands can be any one of the following:'
echo

getcmds | while read -r COMMAND
do
    echo "  -  ${COMMAND#upvoter-}"
done

echo
echo 'For more help on a specific command, type `upvoter [command] --help`.'
echo
echo 'Want to contribute? Find us on GitHub at https://github.com/jamesqo/upvoter'
echo
