#!/usr/bin/env bash

getcmds()
{
    # find all files in $(searchdirs) that start with 'upvoter-'
    searchdirs | xargs -i find '{}' -type f -name "upvoter-*" -maxdepth 1
}

getswd()
{
    ACTUAL_PATH=$(readlink -f "${BASH_SOURCE[0]}")
    SCRIPT_DIR=$(dirname "$ACTUAL_PATH")
    echo "$SCRIPT_DIR"
}

pathdirs()
{
    # get all dirs in $PATH
    RESULT=${PATH//:/$'\n'} # replace : (delim) with newline
    echo "$RESULT"
}

searchdirs()
{
    pathdirs && getswd
}

version()
{
    "$(getswd)/upvoter-version" "$@"
}

echo 'upvoter is a command-line util that automatically upvotes your Reddit posts.'
echo "Version: $(version)"
echo 'Find us on GitHub at: https://github.com/jamesqo/upvoter'
echo
echo 'Basic usage: upvoter [command] [options]...'
echo
echo 'Commands can be any one of the following:'

getcmds | while read -r COMMAND
do
    echo " - ${COMMAND#upvoter-}"
done

echo
echo 'For more help on a specific command, type `upvoter [command] --help`.'
